import Clube from './clube.js'
import Pote from './pote.js'
import ChampionsLeague from './championsleague.js'
import Partida from './partida.js'

//Criação da Champions League
const championsLeague = new ChampionsLeague("2024/2025")

//Criação dos potes
const pote1 = championsLeague.criarPote(1)
const pote2 = championsLeague.criarPote(2)
const pote3 = championsLeague.criarPote(3)
const pote4 = championsLeague.criarPote(4)

//Criação dos clubes
const clube1 = new Clube("Manchester City","Inglaterra")
const clube2 = new Clube("Bayern de Munique","Alemanha")
const clube3 = new Clube("Real Madrid","Espanha")
const clube4 = new Clube("PSG","França")
const clube5 = new Clube("Liverpool","Inglaterra")
const clube6 = new Clube("Inter de Milão","Itália")
const clube7 = new Clube("Borussia Dortmund", "Alemanha")
const clube8 = new Clube("RB Leipzig", "Alemanha")
const clube9 = new Clube("Barcelona","Espanha")
const clube10 = new Clube("Bayer Leverkusen","Alemanha")
const clube11 = new Clube("Atlético de Madrid","Espanha")
const clube12 = new Clube("Atalanta","Itália")
const clube13 = new Clube("Juventus","Itália")
const clube14 = new Clube("Benfica","Portugal")
const clube15 = new Clube("Arsenal","Inglaterra")
const clube16 = new Clube("Club Brugge", "Bélgica")
const clube17 = new Clube("Milan", "Itália")
const clube18 = new Clube("Shakhtar Donetsk","Ucrânia")
const clube19 = new Clube("Feyenoord","Holanda")
const clube20 = new Clube("Sporting","Portugal")
const clube21 = new Clube("Psv","Holanda")
const clube22 = new Clube("Dínamo de Zagreb","Croácia")
const clube23 = new Clube("RB Salzburg","Áustria")
const clube24 = new Clube("Lille","França")
const clube25 = new Clube("Estrela Vermelha", "Sérvia")
const clube26 = new Clube("Young Boys", "Suíça")
const clube27 = new Clube("Celtic","Escócia")
const clube28 = new Clube("Slovan Bratislava","Eslováquia")
const clube29 = new Clube("Monaco","França")
const clube30 = new Clube("Sparta Praga","República Tcheca")
const clube31 = new Clube("Aston Villa","Inglaterra")
const clube32 = new Clube("Bologna","Itália")
const clube33 = new Clube("Girona","Espanha")
const clube34 = new Clube("Stuttgart", "Alemanha")
const clube35 = new Clube("Sturmgraz", "Áustria")
const clube36 = new Clube("Brest","França")

//Atribuição de clubes aos potes
pote1.adicionarClube(clube1)
pote1.adicionarClube(clube2)
pote1.adicionarClube(clube3)
pote1.adicionarClube(clube4)
pote1.adicionarClube(clube5)
pote1.adicionarClube(clube6)
pote1.adicionarClube(clube7)
pote1.adicionarClube(clube8)
pote1.adicionarClube(clube9)

pote2.adicionarClube(clube10)
pote2.adicionarClube(clube11)
pote2.adicionarClube(clube12)
pote2.adicionarClube(clube13)
pote2.adicionarClube(clube14)
pote2.adicionarClube(clube15)
pote2.adicionarClube(clube16)
pote2.adicionarClube(clube17)
pote2.adicionarClube(clube18)

pote3.adicionarClube(clube19)
pote3.adicionarClube(clube20)
pote3.adicionarClube(clube21)
pote3.adicionarClube(clube22)
pote3.adicionarClube(clube23)
pote3.adicionarClube(clube24)
pote3.adicionarClube(clube25)
pote3.adicionarClube(clube26)
pote3.adicionarClube(clube27)

pote4.adicionarClube(clube28)
pote4.adicionarClube(clube29)
pote4.adicionarClube(clube30)
pote4.adicionarClube(clube31)
pote4.adicionarClube(clube32)
pote4.adicionarClube(clube33)
pote4.adicionarClube(clube34)
pote4.adicionarClube(clube35)
pote4.adicionarClube(clube36)

console.log("TIME SORTEADO: ",championsLeague.sortearPartidas(pote1))

